### ISSUE TITLE
how can start in local

### ISSUE THREAD

**Issue by mbf5923** [gameeapp/sample-game-spinner-winner#2]
hi
can i start this project in local without need internet and gamee emulator?

**Comment by EntityB** [comment]
Hi, 

shortly said, yes can run offline, but needs the emulator. 

Game must run in the iframe where it waits to receive responses from the parent window. Gamee-js framework requires the other component to communicate. 

Emulator is the mockup component that doesn't need any backend. I'm attaching the zip file with the emulator. 

[emulator.zip](https://github.com/gameeapp/sample-game-spinner-winner/files/1387684/emulator.zip)

Unzip the file, enter inside and run some localhost server, for example:
`python -m SimpleHTTPServer 8081`
Then run the spinner project (`npm start`)

Open the local address where the emulator is running (targeting the other localhost with the game)
http://localhost:8081/emulator.html?projectUrl=http://localhost:3000
